export const FDDHeaderRow = [
  { label: 'Id', key: '_id' },
  { label: 'Name', key: 'name' },
  { label: 'Category', key: 'category' },
  { label: 'Description', key: 'description' },
  { label: 'City Code', key: 'city' },
  { label: 'City Name', key: 'cityName' },
  { label: 'Bus Code', key: 'busType' },
  { label: 'Bus Name', key: 'busTypeName' },
  { label: 'Country Code', key: 'country' },
  { label: 'Country Name', key: 'countryName' },
  { label: 'Supply Id', key: 'supplyId' },
  { label: 'Corporate Id', key: 'corporateId' },
  { label: 'Supply Type', key: 'supplyType' },
  { label: 'Rate Card Type', key: 'rateCardType' },
  { label: 'Active', key: 'isActive' },
  { label: 'Rate Card Hash', key: 'rateCardHash' },
  { label: 'Deleted', key: 'deleted' },
  { label: 'Created At', key: 'createdAt' },
  { label: 'Updated At', key: 'updatedAt' },
  { label: 'Hour Threshold', key: 'hourThreshold' },
  { label: 'Hour RoundUp', key: 'hourRoundUp' },
  { label: 'Rate In Ride Km', key: 'rateInRideKm' },
  { label: 'Rate Out Ride Km', key: 'rateoutRideKm' },
  { label: 'Rate Threshold (/hr)', key: 'ratePerHourThreshold' },
  { label: 'Rate Overtime (/hr)', key: 'ratePerHourOverTime' },
  { label: 'currency', key: 'currency' },
];

export const LumpSumHeaderRow = [
  { label: 'Id', key: '_id' },
  { label: 'Name', key: 'name' },
  { label: 'Category', key: 'category' },
  { label: 'Description', key: 'description' },
  { label: 'City Code', key: 'city' },
  { label: 'City Name', key: 'cityName' },
  { label: 'Bus Code', key: 'busType' },
  { label: 'Bus Name', key: 'busTypeName' },
  { label: 'Country Code', key: 'country' },
  { label: 'Country Name', key: 'countryName' },
  { label: 'Supply Id', key: 'supplyId' },
  { label: 'Corporate Id', key: 'corporateId' },
  { label: 'Supply Type', key: 'supplyType' },
  { label: 'Rate Card Type', key: 'rateCardType' },
  { label: 'Active', key: 'isActive' },
  { label: 'Rate Card Hash', key: 'rateCardHash' },
  { label: 'Deleted', key: 'deleted' },
  { label: 'Created At', key: 'createdAt' },
  { label: 'Updated At', key: 'updatedAt' },
  { label: 'Start Date', key: 'startDate' },
  { label: 'End Date', key: 'endDate' },
  { label: 'Fixed Amount', key: 'fixedAmount' },
  { label: 'Total Buses', key: 'totalBuses' },
  { label: 'Rides per bus (/day)', key: 'ridePerDayPerBus' },
  { label: 'Max Rides (/day)', key: 'maxRidesPerDay' },
  { label: 'Max Distance (/day)', key: 'maxDistancePerDay' },
  { label: 'Max Hours (/day)', key: 'maxHoursPerDay' },
  { label: 'Extra Ride Charge Type', key: 'extraRideChargeType' },
  { label: 'Extra Ride Charge (/day)', key: 'extraRideChargePerDay' },
  { label: 'Extra Distance Charge Type', key: 'extraDistanceChargeType' },
  { label: 'Extra Distance Charge (/hr)', key: 'extraDistanceChargePerDay' },
  { label: 'Extra Hour Charge Type', key: 'extraHourChargeType' },
  { label: 'Extra Hour Charge (/day)', key: 'extraHourChargePerDay' },
  { label: 'currency', key: 'currency' },
];

export const menuItems = ['FDD', 'LumpSum'];
